### ISSUE TITLE
Copy and paste support

### ISSUE THREAD

**Issue by AArnott** [dgriffen/WhackWhackTerminal#5]
Please. :)

**Comment by dgriffen** [comment]
Shift+Insert is capable of pasting, currently there is no copy support but I will put that on the roadmap for 0.2.2

**Comment by dgriffen** [comment]
I'm considering what the best options for a copy paste shortcut would be. Ctrl+C and Ctrl+V are problematic in that they have other uses in a terminal. It would be easy enough to make Ctrl+C contextual based on if any text is selected but Ctrl+V is more complicated since there is no good contextual way to decide the shortcuts function. I'm open to feedback on what the proper shortcuts should be.

**Comment by AArnott** [comment]
If it's good enough for VS Code (I think it is, IIRC), I think it's good enough for VS. :)
